# Generated by Django 2.2 on 2019-04-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=10000)),
                ('tone', models.CharField(max_length=255)),
                ('emotion', models.CharField(max_length=255)),
                ('professionalism', models.IntegerField()),
                ('offensiveness', models.CharField(max_length=255)),
                ('reading_level', models.IntegerField()),
            ],
        ),
    ]
